// <auto-generated />
using System;
using CompalintsSystem.EF.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompalintsSystem.EF.Migrations
{
    [DbContext(typeof(AppCompalintsContextDB))]
    partial class AppCompalintsContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("originatorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SocietyId");

                    b.HasIndex("SubDirectorateId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Compalints_Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("Compalints_Solutions");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplaintsRejected", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("reume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("ComplaintsRejecteds");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Directorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 2,
                            Name = "شرعب السلام"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 2,
                            Name = "شرعب الرونة"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 1,
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 1,
                            Name = "الحيمة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "صنعاء"
                        },
                        new
                        {
                            Id = 2,
                            Name = " تعز"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الحديدة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeneficiarieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmeted")
                        .HasColumnType("datetime2")
                        .HasComment("تحديد وقت ادخال الصف في قاعدية البيانات");

                    b.Property<string>("DescProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitileProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Societys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جمعية البن"
                        },
                        new
                        {
                            Id = 2,
                            Name = "جمعية الالبان"
                        },
                        new
                        {
                            Id = 3,
                            Name = "جمعية الحبوب"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StagesComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StagesComplaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "العزلة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المديرية"
                        },
                        new
                        {
                            Id = 3,
                            Name = "المحافظة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الإتحاد العام"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StatusCompalint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusCompalints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جديدة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "محلولة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "مرفوضة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "معلقة"
                        },
                        new
                        {
                            Id = 5,
                            Name = "مرفوعة"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDirectorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.ToTable("SubDirectorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorateId = 1,
                            Name = " القفاعة"
                        },
                        new
                        {
                            Id = 2,
                            DirectorateId = 1,
                            Name = " المخلاف"
                        },
                        new
                        {
                            Id = 3,
                            DirectorateId = 3,
                            Name = " بني سعد"
                        },
                        new
                        {
                            Id = 4,
                            DirectorateId = 4,
                            Name = " الاحبوب"
                        },
                        new
                        {
                            Id = 5,
                            DirectorateId = 4,
                            Name = "غوبر"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeCommunication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeCommunications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 4, 17, 39, 24, 198, DateTimeKind.Local).AddTicks(5974),
                            Type = "تماطل",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 4, 17, 39, 24, 198, DateTimeKind.Local).AddTicks(6010),
                            Type = "تلاعب بالحلول",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeComplaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 4, 17, 39, 24, 200, DateTimeKind.Local).AddTicks(4010),
                            Type = "زراعية",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 4, 17, 39, 24, 200, DateTimeKind.Local).AddTicks(4893),
                            Type = "فساد",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UpComplaintCause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadsComplainteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("UpComplaintCauses");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropBeneficiarie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("StagesComplaintId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCompalintId")
                        .HasColumnType("int");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("TitleComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SocietyId");

                    b.HasIndex("StagesComplaintId");

                    b.HasIndex("StatusCompalintId");

                    b.HasIndex("SubDirectorateId");

                    b.HasIndex("TypeComplaintId");

                    b.ToTable("UploadsComplaintes");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UsersCommunication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BenfId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Titile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeCommuncationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SubDirectorateId");

                    b.HasIndex("TypeCommuncationId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersCommunications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "48e9b2f6-42e7-439f-afa2-03cf13342517",
                            ConcurrencyStamp = "2e591243-d191-415e-8e0b-472f1cd9b51d",
                            Name = "AdminGeneralFederation",
                            NormalizedName = "ADMINGENERALFEDERATION"
                        },
                        new
                        {
                            Id = "2afd97e1-b763-4a31-9a5a-0ed57efd7a04",
                            ConcurrencyStamp = "a7bf984e-2474-4c05-a410-ce9e7de97221",
                            Name = "AdminGovernorate",
                            NormalizedName = "ADMINGOVERNORATE"
                        },
                        new
                        {
                            Id = "f4af62bf-7d40-483a-8ec2-8fa0e94b8337",
                            ConcurrencyStamp = "6b426ab9-0e5e-4118-baab-a30ef5068b03",
                            Name = "AdminDirectorate",
                            NormalizedName = "ADMINDIRECTORATE"
                        },
                        new
                        {
                            Id = "2031d8ec-c362-4f84-8e3e-97a28b8db091",
                            ConcurrencyStamp = "03afe4c9-7e22-4125-bd88-4a57d1185efd",
                            Name = "AdminSubDirectorate",
                            NormalizedName = "ADMINSUBDIRECTORATE"
                        },
                        new
                        {
                            Id = "b7d0b985-a65a-4490-9789-58bb772c1386",
                            ConcurrencyStamp = "f5b1cfef-09b1-4b28-aea9-609b87b09c10",
                            Name = "Beneficiarie",
                            NormalizedName = "BENEFICIARIE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Directorate", "Directorate")
                        .WithMany("Users")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Governorate", "Governorate")
                        .WithMany("Users")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Society", "Societies")
                        .WithMany("Users")
                        .HasForeignKey("SocietyId");

                    b.HasOne("CompalintsSystem.Core.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("Users")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("Societies");

                    b.Navigation("SubDirectorate");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Compalints_Solution", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintsHasSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserAddSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsHasSolution");

                    b.Navigation("UserAddSolution");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ComplaintsRejected", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintsRejected")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserRejectComplaint")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsRejected");

                    b.Navigation("UserRejectComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Directorate", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Governorate", "Governorate")
                        .WithMany("Directorates")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDirectorate", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Directorate", "Directorate")
                        .WithMany("SubDirectorates")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UpComplaintCause", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.UploadsComplainte", "CompalintUp")
                        .WithMany()
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "UserUpComplaint")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintUp");

                    b.Navigation("UserUpComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CompalintsSystem.Core.Models.Directorate", "Directorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Governorate", "Governorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId");

                    b.HasOne("CompalintsSystem.Core.Models.StagesComplaint", "StagesComplaint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StagesComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.StatusCompalint", "StatusCompalint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StatusCompalintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.TypeComplaint", "TypeComplaint")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("TypeComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("Society");

                    b.Navigation("StagesComplaint");

                    b.Navigation("StatusCompalint");

                    b.Navigation("SubDirectorate");

                    b.Navigation("TypeComplaint");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UsersCommunication", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.Directorate", "Directorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.Governorate", "Governorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.TypeCommunication", "TypeCommunication")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("TypeCommuncationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", "User")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("UserId");

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("SubDirectorate");

                    b.Navigation("TypeCommunication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CompalintsSystem.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("UserRoles");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Directorate", b =>
                {
                    b.Navigation("SubDirectorates");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Governorate", b =>
                {
                    b.Navigation("Directorates");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.Society", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StagesComplaint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.StatusCompalint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.SubDirectorate", b =>
                {
                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeCommunication", b =>
                {
                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.TypeComplaint", b =>
                {
                    b.Navigation("UploadsComplaintes");
                });

            modelBuilder.Entity("CompalintsSystem.Core.Models.UploadsComplainte", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");
                });
#pragma warning restore 612, 618
        }
    }
}
